---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  annotations:
#    volume.beta.kubernetes.io/storage-class: "my-nfs-storage"
    volume.beta.kubernetes.io/storageClassName: "my-nfs-storage"         # Larry: updated to "volume.beta.kubernetes.io/storageClassName" to avoid warning :: storageclass is deprecated in v1.6+, unavailable in v1.22+
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
