apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:gVGEkg4R8Oh5+kMjQZsfurrALO/cS2NE7ykIZlsIaGMuHBYomem8aA==,iv:LfY1uLG6b5s40tPmwo/WonohpY3lln7HGHZUlK3zHUI=,tag:hCFEd0LKOo/xqyjsu0OdZQ==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGN0ZSaFZFdnF2OEtGZThl
        YlBQRUt1OVJ3NkNYOFp0YTI1Ny9aWDIzOFFnCnliTUFnL1c2NXBQZVNBdTVaYUpY
        cEJ4Z3hwd0ZneWxRZnJlMDRtOENHMmcKLS0tIGtFZlBwd09sSUdOM1FvaEZ4OXI0
        dWovU0VGUHllMWp2Z1V0V0YzWXJ0TncKubs0tituQom+TMBXpuQ/LYHu8+cOEkCy
        OpHxX20cj10/iEYGTNR31CUpIjUw7uvdZbfGGqIdmeOlxi6sL0sHRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T02:31:21Z"
  mac: ENC[AES256_GCM,data:rfXBSLDm+AXSZSxQy8pFWD76wlrP8rIGeUxEzKm+bSUKzAEVU4aiMkH1IzfoSOhtj0SMPGKNu/MYOkeH5yCdVWZ3zgNBpihd5gcpPy8zXz0W3Lx1u18DZMhivR4nVDHLzkP2yKeRxenAS/mwAv1mWO42uQ3T0x/IaaO8qdc1T6c=,iv:j9qijO9pGJGX3eg/NUU8NIH0GKFogYorB56bCUc9C7A=,tag:J7wqDjG1jBiPbyMIwJTVCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
