apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:OAiw8d5hdgiOK7Zi36JblpTPu5Y5ek3bEyDs2ZgKp4kU//6MFpDV0Q==,iv:PQl3KkVz94nHLCpbrHZvQWTzcZc9i1K5vRbyMyY7Lvg=,tag:hTvvx4rve2Zp8Yj35pD2tA==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbS9tTmRrWUdzMkNWUjNC
        cUUrdDJnZnRQcnppc0lWVHMxQzZVZVUxRUZzCkRCT2JrSXpJZ0NQd0gyN2oxUlRB
        cDkxaWtzZnVGd2NjdXhHVFlSYzNpRTgKLS0tIGxObU1ER211VEhsd29zNDNLNnBQ
        MGhBL0RLKzkvWExiT2ZRQkFGU2I2dkEK8nA9jFt2VvPm5JsYs5E2nX1pzWYP9vln
        vVp5FnSrYTBjaHajhHGqGrIbTVyh0HLakao3CGqkObnZrBdGTM2WYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T04:08:53Z"
  mac: ENC[AES256_GCM,data:f04pIJgYfDbH0T7dRwwIAto09u6VF2yE/idlUOZU7wgLQxukwsucr/ZLcin3cmparu55D4HODB3OwqVtp0Twq5E8PDl53XcAfi5P0MxF8m3f9C0UN6RTqg6DbpMnWoX9usGmGLXe2b4OFsbVNtVQNUtDzDJJ5Cm44xneZgW5XjQ=,iv:wokvgVmSVoGqxirzqwYjQiOei9LdzcpZ6ooH7KJ4+7s=,tag:kMJIUCuC2v4WVgwL88HCug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
