apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:+ksyUXYg/02lJAuvY1EU2KNhYP5is2B7cwFwHpGjY6n8NyKScBdeTA==,iv:RmWURL3MIqNYiblWmfTI9RojZhxzvN0lTeStosajmTo=,tag:XYbB1OrfcPCoYbLit/I/iA==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZC9Xb1Z5ZmMycy9vT0FZ
        b3gvVHlxRlFVTnR6eFhza2FGdmJleWYzRFR3CnlySy9XUkVhN1dISHcydCtXV2U4
        cHZDU0pOQ0NkM0M4QnVjSkx5OFNRTWsKLS0tIGxGYXNQSkZMVzZJdDdUZkZaY2JZ
        bmRqTUVsN1U4bVFyaEloUlUwcS9JcUkKIzIADfegpXVXCdVxmcXtDI2equg4Sq0c
        twh+0rO+X5TpaQEnRTYQR1ldPgYmPopsUNT/kilEb9YutzLtPUYfqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T00:57:17Z"
  mac: ENC[AES256_GCM,data:JGqX1f9LXGXSacKergYemkX6x7Q4FSIktWE3QnLCIhSJo6Z8PtKrTYEa3eFWpyRvBxUb4shybaETV+uvlpP4l45ASy5XxqGXT2vvKHFGOKEUzR1xfAfLP0wOhAURNm9QTpIOYbf9q1cw2PhTbCWVl0gJuQVWpezGc24RoXfIrW8=,iv:Gznim1F8cAhyDaxD899Q8rLo0dBcpjJ5thbPdFUrnvw=,tag:RCg+JglEMsk+IxwuxBV9Nw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
