apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lBdbwfpnRZFozCc=,iv:wWyaHQAneOVYZKvvvRQjFF4qp28tm/SUF4zxalR9tqA=,tag:o+lmJSNyXGSmWd4VmrNl/w==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSHgzSmpYK2UxVlJzQmtS
        RndXTGRvMGxmLzVTUWdmU3RlSHFFUmdwQkQwCkZpNlhSdTBreGxWT1piZGgyMktN
        OTBMUXlpZ0JVWGRTMzh2VnF6MWVwY0kKLS0tIHNRL1dRK1plZ29ndG01WFhvL3Y5
        RG1DWHVLVXNEc3IzQ2paL3lMQWI4aWMKiI34axAhpLCpe9EvyIvhFEDwtQp8nLwR
        YrtmwDHt68eRgadC7/uxzOlt6alYnts62A6IH5Uo3jqdzAFyqwp7sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T02:31:21Z"
  mac: ENC[AES256_GCM,data:ENqL6kFyoiu+m8u1/9QkirN+iJaIP4hwjZZcQzxr8tPObq0TzY8e/NqWssVmMoVZ0FnH6taPwaRc4KPUH5WAxDVn9hqR0AfuDZwCtSjto9H4BydgSP9zikUJz1hLAWU2byi53Jg74grIrOvwid2Xl60UssY9XNYZ/i0++GioJb0=,iv:6RmDTO0FxStvt8foC1Mj5iHJRygggflCq9WZnDlsGT0=,tag:PFRFdnsjYsfVz24Td8la3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
