apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KaAqDuo9zLo+i5w=,iv:A+s9PxyqXMTAQCiwNKEQySKD097/HQHVTJwqQSpZuFw=,tag:p4RpyPMraWqb6DHq8ZEiXA==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWW5WQkpMUjRDR3EveVRY
        NUNVZkdWa1R3Y0xSWU4yQndYQmpDcGwybEI0ClpyYzROV2xNMmoyVDlzRjR3Ykhm
        QTRVWXpBeHQ1citaUTU3VzVwU2FwM1UKLS0tIE5aQ0hXWHRQWUd5ek0xMWZuMFN6
        TFh1Mlh3ZU1jdEtpQm92ODBwTDVWbmsKNsd3c5DrXm7Bu412fXacJkBbgb/1R4Pk
        nX3mZWGlxUOlyjAysNAwHiSka+UkBz3Lh1GrNHbGRbHLUhsgA/okNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T13:27:38Z"
  mac: ENC[AES256_GCM,data:JTb10bPfXZIqZDJz1Ba3StrDkh+34q6s9Wkwo9Qi1eM5HuH1nTB+F1WZYOSzVuL1tKc/mLFuealqgi4OvUDoePGbtQUF3AH1yfmu/8+9tXeOeba+RJHZRUS6gaFRj9LP/sKardHj+Jngkj9FwSJg/Ar2BM/upkIQjB8254pDBl8=,iv:onp2OrVV2VdKtz+BfIjK6aVoZ63juctZEgw+tePQqSE=,tag:UCUAmRZi1IlgoURQieujNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
