apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:29MnxykKGWaTNdE=,iv:d1GWx4HwYLphEWCZxRqJO+6uAuXh8zeu8JfcxruZ6wA=,tag:M12AIL/Kne3nJrPns0cpBw==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTWdvVFl3bmJsR3BtT3hD
        aVZQTS9wWEJaWHRNWmFSdHFMUkVTa2tUbUFJCk03ckYxdjRETHNmTG5LejBobFpv
        cmhVdU93VnpwYUh6anorZHN1eXg2alkKLS0tIHVXUURxWWdhTjhIcGhISStHa2tD
        NUZJWFNvZ0t1cG54VVYyaDRrYW1udzAKvplZi2Qh6Wx/nHHhmx+lJ8cNMvoksjgp
        77hZwsFUefxJpCxlem5+Ug8BRY7VJRcY93oN/NYoqgWa/z13vExfEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T04:08:53Z"
  mac: ENC[AES256_GCM,data:/3YgGXMoQju8KqLTzjdkSVcvLmNmksQWmpLL0WC1cQowRYa6nKBoPABeyKpWoXoBjN2qkDuIGbtIj5eQHGL8z2Xjeu9NGt4AcjWe83izU3aBMpvKvHzDzQ44McabY07FAlt1FZLNa5XYImQAq18BVN7hLYlu4MDbpAG5W6JcXic=,iv:iiZOuQcweY1mZf2uAP0Gs+cwWzIKZNBPrvcduYCzpUs=,tag:RC4cQQuWnZ7WOvo9T7poTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
