apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:On7k/31iAS+lA+iO78f18LKHwlYc53yTL3vvrN4UykA=,iv:SANmtba80ezXNsBZccBFP4YG+WaS90vs6TpMuJSDZIA=,tag:eCfMlv20r98m7xbGFubd8A==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1emdwZk9ZRWdvWDljR2xC
        MFNQVjA4Wmh5eGFyOUt4SUU4Sm9IREJiQ0hFClRFOHM0bE11TEtCek1Md2hkSkhZ
        RE1aQXY2R0xyblpSWnV6Z2dvSEFHalEKLS0tIGZBQ0hNNFRrWTFKcXFwQ3JIRU1u
        ZFNZQXJmMFJUZElQTkplSzVCZkQ0OW8KLa2oxS0JwA6IJ/hKNFLABqkCgdywuNQ3
        JuxAOrAVOt+SvxEVgzi2ZqSHkdOHs+hcV/tR6gaBxEMRVimaEMirwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T13:27:38Z"
  mac: ENC[AES256_GCM,data:wgjfH22+asLz8i8MdqgsBHqcpU+s4ZDNeMj4b8iuXxQwFG6kf3NrhqA3UFcSKJq9JWbPP/iRmBDJK8GiZiwi2qlDKOwFCkHPb4vYLBRjhhDJSkMioRIJLwW08hM4mRt7PydDi3utr2MjRCnmYRBllWlF/Q2QBeOu2lQ4sH84yt4=,iv:2DcA6czu7uYpXRBgcEBkrnIg22qB8FZZmXWKwPF+Ohw=,tag:lVrDsv5v7yo+BQsVHKX11A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
