apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wph9gdPp9WM+Gi0A82wjxzlFktOLPJf24GtWHw6RL1I=,iv:DmGEhNeZT73WlOkJmKyobS2R1ST0Sj2hqqnGGWqKVEM=,tag:GNKlPXLyhOZmp9EBeOXyVw==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNXZkSjc3QnBnYWJ4Ry8r
        am5NazVtbENEN2pMaTNEZzg1L2RNbUR5eVI4CnloMVBnc0c0eFJHNXpxQ0R2L0wy
        N3FWUk9zMjVZMkI5WUdVSDNBUXljQVUKLS0tIEkwN05iM2d6T3hFYVFUVXpHalM1
        K1JqeS8rN3BxdVlEMHFFdVBMZXEwbHcK1ZwdBGK1Rls9gHNJfyuO6XobD5hfZkwb
        fcaUC/JtktOHA9hWuWIM1eoiPgLGq767Urt1NIyd/+WcL9d4NONavA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T15:15:10Z"
  mac: ENC[AES256_GCM,data:bLzqmX9Rmqb0Op+hWJ1Any8BxYX+7fHu+vv9g2NhrChEsDinjUE2C07gUckHR5kdhbTJBu5Vxtn8Q4FSPgZeav4X5UU8XiOSow46lhMDIuaHfkeuGTQziMcRWxHBLK6VTopJKViDdza4UEHdKNSnVIZNQziqn3EFI7SROn5gWqQ=,iv:xPo8VAJn85BpNXf5nOWDlGRQgiCUjbEkGCy1+1+3TBI=,tag:+WKqt1z6b1OLaImb9U8sKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
