apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:gd4pbLPn9eW5cbjiO7YYHDVCLMhLfFihNuF662FgSC4=,iv:dCWW97r7J00WJQBYMxxQ8tDsuepLrBeQpMNtDasBw2U=,tag:UW9H/wa5r4UzzyNg9wzzpg==,type:str]
sops:
  age:
    - recipient: age15u38xwergelq3yt58cqe6aytdkhywda8993y53tewadsxeegcc3skuk6cg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQVJ5ZTlQWGc5K2VEVmlX
        aHVzSFdpdmdUcmZHb2w2VjFwaGNVcC9FUkMwCmx3QW9IMG50bTkrSTIya2hCQlFq
        Y3VFTzU4WTROL256R0h4UnNDRzlSVmcKLS0tIENpUlZoeUU0dXJRT2FNSU1LN05V
        c0g1UFJRVmdpaTRLRVUvRERNRVJ5YU0KhuDbFz1BcYUxtBvw/VRyojv5VMQshZq0
        FqqxscWmmdOlpnhlXAeNj1p8vRdd9xwEs2GIFoNMqazl2HLu/ILOkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T16:01:14Z"
  mac: ENC[AES256_GCM,data:1FD1cbMwLLTr8hjSMFplSvmadQVYvyTn3fYxumN3MkrRmNoVloj65OodmME4PaGKBQpFJH2jXZ1YGPtt5n22Et72GGG5qFZBkgI9B+pogAuEfo34CsTwhRqz+cfGbE294WyQZJ+BmIqMHda+zzqWDFAeuQwMrJoPvaFFQd85mB4=,iv:2iVmrChRDNyjn8B1K3Z26kX0r62X1SC3ouwuF9uhJfA=,tag:nM8uS1zFhF12fApGS2cfqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
