apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:/5yQ3ciPBug4Ls25xrS3nchxikCPD5Ta3P0u+PM9vyPkxkT0kBtVLbO4bX6u3JlXmantAC+05FejwgEyBGFCLUjSfm4xpl1kg5NVmRQocZSxoan73zVKoT7MFwEWuogAAYpZET+d21W4SpJmPlyLNPyE6FtnKEBV/Ih6/fL+7YailH5LZK1pPcJX4oSKjav4MITWHyPqTmxRrW2qRcGUy5pAVk1RJ3hUihdP2mC5NKU9TsX5,iv:mffqZEZWj0PaAPPNaUAPIcYJ5V5ysIycnII2+MsSRfc=,tag:g8voIt93FbxX6h2ticFaUg==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib290YlVOMHZrY21zakRQ
        VndoOExFS01acTc0K0hEODl5cTJtUUFkRWpjCjVLYkVreEV0TkV4eUtFVDV1WFhh
        RE0ySGIzNjYzMEFtak5JRHRFU003aE0KLS0tIG5UTysvb3FpSkJ1MW5uejljY1dQ
        K21DMVJCTXU3ekFOMzlEcDBaV2ZYMzgKqrjB0Wt5zu1CGcBp6btmCXXJgoRZ2swZ
        I8lkb9u3BTy9zUyP95RbLhcQm6E3GjUHdRDS5uyy3viJWZxjva8cuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T13:37:50Z"
  mac: ENC[AES256_GCM,data:dTBHUXsIQ8nO6GYDjZ1AWJeLCzSJuJ2WAWpDkBzZGU72woXQysvER1wRimxgBmQBvAY1UhJZl8MRli06ekHItZGobGtteJzHs1KXfbCFelUJbK9YjW5QaoHfWAl6zOWLlU6e3lWg1NTVSGmnhgEcfo6PmlKJH3T6z60FWQbjwvY=,iv:bAzRpryw3tBsDDKpPJ34icavRtHdrWDaJAJIEz0k4Co=,tag:G2mO63GuMdYwe/E3aW9zHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
