apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:29lnBtEaSDP6OYUOeYXoO46iN+I7/cxuuLIfYXKwGnSAdQMCaitpHk5pSN0ZegtPYJ1dg53q6T63TVycIUC62aI9rAQLQNmSrxBuFBUXmqQ3MamslHuUDE1y8KdgZeyOX/ykhNFOKNIosOHwDWYHv1fpJTTYUnmKU84FvaALSwTVFpqA6GSWwFw959X3vbs5k9+LsTfPBq8oyu79fuYcVirTMQx5Nav4D4ORZfuO2ie+v42D,iv:jXIha2ENEqsr4zoiBfeBAAOUhL93581Zkb4nfglqJkU=,tag:VidPAVqTJNwdJOMM5Hr9Jg==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENm80NmVKYS9NU1pmWVJ5
        L0VIT3hMUkNjMDBRTWNnUjBzTXUyb2I1Q3hrCjc3SHU2dXdzZTd2Mm1Ha3J3UURs
        Q3hIaGdOWm52NG5mNmpiakhGWEYxUEEKLS0tIEZVQkt5NEZYdGwrNEdrc29pNWpa
        b2x0ajlwYXFGL21qUzRqcEhpdkRqazgKaX3VocFpCCeJspVHeRPeCX9dZLSS7UeO
        7dwHKAw1xr2Khcw27q/rGZMDWPq1sTyVHMniM0cMB2wROT0Ouora+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T04:08:54Z"
  mac: ENC[AES256_GCM,data:XvaqmePC9CiYrbRTqniunf4pTL21uwW1au0U/Cl6hrv4LUrz0j5GI+8GQUFUQSk7oae7SsxKPrL7/yaPgdxP2ZQgTf4FiE25vi/pe9DDVnKflpfw8PhK2LLgddb13Oj0KafVhBF6h1ZKT8c2o14tYWKTZmkHnCIe4M0oUaV7gqM=,iv:poAFJIomXCirwoiZebMJJvVpXuHxsVDtjQbDUEi/dHk=,tag:VmaFSzLbeOHOQGZLcFR4Vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
