apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:WKjojhQ30Zt4DA8AwnYRwGnYoylT81huTxmBow4yefuiY2rcqJpXIYwczZNxewPK2cN8egEH8rn6yZctZhVqrlKwpn7B9ziiDyuKWLi0Z32cby/bLr/xTQI50SrhCw4x6CuapLM/PmIVbwkD/G/GmK6cO1+/NghFGbNqeQkvBhfxd0HH+eO4JrrBJC9D1XPrGSNPBpcp398zO8sx7SOuyipqsybddscbW9e6R9sxLRM50wBU,iv:jZYLUMlu5eZuo7xxBnlfWpJ40LG90ZvsDtYsiZ8BaUU=,tag:Oybf/i6Jt3MtS5+4wBnQWQ==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJazBjS0tsMVF6WWpNZjRp
        eG01Mm1jdlduL1ZVWUw0a1BBalo4eE45Y3pRClRNTzdkVEN3Y1lYYTZZOXJBYlpH
        N2xsWSt1eGQraUY5M3hIRVhIcW1abFUKLS0tIGtjUUVRU2ZGaWlhV1RhM3poTFFQ
        S0NzNThqODZoeFluMWFVUndBbDBycXMKTgdGjkelHQN5EqzVraGv+XHLkSYuuJD8
        7e5BeYMQNUgitbzt5fJ4g37nRXv97Fl5sQCXCJQ8LMLK0T4TeakAYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T15:15:10Z"
  mac: ENC[AES256_GCM,data:ymkqF3hZSu7nsH0nzwMVUOI1EQBe7PiIq5u32nWpJ0FGo42s9/xZZ3OKyGB8jLVTP0ci2uSV/gM+p8+qa5ke+OmeeHIRsuZi0eY8vgq3IzLNqeLX7EFAMxiponxSLi/Jkej2VdW5P3qOJZpcr7on4QDRvoJW2G0gd4s9De7eSSw=,iv:HBDLOe9kquny7+vs17DPD1YJtMxPpVj5449ypkjiAEo=,tag:/WqA1TJ96HfAoVbVZisHdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
