apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:83DDq4xzSsnabC1wAE3kN9VPYdQovVS965ot8A3mfDGhHH1hWETlIQ==,iv:X6WEG7rm1ozH+KteIvJPalLgt+2D1xDCnyjGfZPLdbs=,tag:MvwL43+XfiULmRzYI36Ttw==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZkphMVM2WHNteG05djh1
        ZEc1bE1QNjg2SEVtZWJsc0hzN0FCUDNFRkg4CmRWanAzYjR5UmtMdWZKc2xTUEJj
        SWQ5Y1h5T3pHWnFYVDVadVI5TDFKU00KLS0tIFhSMmhYazhpbnNrZFlKWTFRQ3py
        SGx0enNTYUZweWtGanhiampld0sxUjAKq0hyn8//462EHor3bS9LXRLj9c6UDB7e
        8M9ZlvnIaQtI4OmNKbfJJ5K1Ux2TbbRHbn8zlvNEdZD1hW9cM5UUXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T13:37:50Z"
  mac: ENC[AES256_GCM,data:iBU+N9zHapuy8RpKh1MH5hF0m+R8XrU7gfI3Qet0NPPwz2jd+x0TDOpxG18rIVBuUnAutK8NBeW75e+ZCMihzkO0FJG7gZ58D4DfRI3h4esr7PXE2x3T7/MmmTpimTZVMRGuUCNKJ4K+MQzVPphu+bRXyUfvX8Yn5hroAO9uei0=,iv:nVK2P22CUKWZZ8tZ6cJFuQWb3jdjr4qpwibiNLItx20=,tag:tv2rB4hYAkC6KZJ+d/8NCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
