apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BCwyYbSg+cFa0Z1hx8hWRIWPIy+JTz++tHPIJSo6eM/NFB7gjwNFzw==,iv:mddvWMQaj5+G0q4D/cn54VgviaojhfwiDbwpT5qHFD0=,tag:0bFku41pF2XTTLeOQ9DIQw==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c3I1MFdLSUJYV1QxRWwx
        S1FIZG4rM0tQdU9IYjZrTjlLTngyOUI3OWpJCjgzTGVVV3JtQ2IvSW5acjl5R0F5
        NEdWZFNNcWZSamQxVThUb3poTUpKeU0KLS0tIDFGd1RUYkI1cU0yTHdMQ3htZWJS
        SFBTSEJ3OEtVWjJ4ODNNTUxxZmJFR00KAnFWtB8vfE/t7RgjrRTZUP3+W3oRzXi9
        3TWVq9p+iaTx8t7udXxRQiewPY1gp4a2Tmtaq0Mfg1smc8ez665JEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T14:54:34Z"
  mac: ENC[AES256_GCM,data:1WEI9LlbgMUZNKRu5dI9btenKjE9UbBMKtPlgJpgUky0HYh8zaCCnZtv0iSFYP5JS1K6lokVtyLmh8FRzt76RrNQaY/F80Hzfu8shavpd7j0yFkrkRaB/WrRZlntDIn3/NGPmnp5bpjJtBqVtnMtfE/Gnfll9ihsdv37hiF4zjc=,iv:aLNLxJn5ItBp4FPngb58jb3F+Sk34Inir2WPdIUMjBM=,tag:ASFj5Sp75cbcRErmb72k8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
