apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7UezpSSi4rYRk08mMy2gojj662lG3W4GoG3Avy+6quGlvqOWfNGACg==,iv:gjakstxP6WwSZycKSBsuaqlmamV2YzhJyrFVaLSEM6M=,tag:RnsiF9Mx2gbTQw4gjQTIkg==,type:str]
sops:
  age:
    - recipient: age17tuw68llsqejc95mjrw0rnjurtn6sckh9d9j35rzgtm4mmykyvlqwscaha
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdTZLT09lWUlqNUJJTVlv
        bGt1cHhlWm9yeE5kSFp2VTFWSGZ6ZXFFR1IwCjFzSFJRRkJtcjA3dFJJUjJOenNE
        bEJjWjNheHNMQ2txbDVPRVNMb3dDMjAKLS0tIE45SENtM0luU1VpR0JlY3FXUE9H
        VVVySW82VUpCZ2RpallLWm9BRXRLY3cK1IFkRgCWgoLUEejgrViZG64aLF6Cy/u2
        Seo8Do0tRGD2UlbMS2xUh2IRj7aowWCntNeRCz5DiuCrCU6EIiRr6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T14:42:20Z"
  mac: ENC[AES256_GCM,data:dumBSn8g4sYTzlk4EJZkeMeJtPB/VGal1wKBW50mRa8y3qCl6r7SCIH1xZepYxhvnKmzMVkiLFP70CNI72k4pzwpFTuGcfBUVw6Kxtj8Iba+M3Hc7C3lhmKt0LSVNIsGZBCLG26CEGeb839wy+hVAYFmMshc8Zni7X0cn/tRegM=,iv:irzte4wHQZeQB6x0WYLTskLfeRV6zb52giQJxCPGyJg=,tag:pGU2TyO0tJ1uEu+4+3fetg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
